### ISSUE TITLE
Any particular reason for choosing mongodb?

### ISSUE THREAD

**Issue by alex-nexus** [froveda/ipsy_shopper#2]

**Comment by froveda** [comment]
@alex-nexus I've have been using MongoDB lately and I feel comfortable with it.

- It gives me flexibility: I can add or remove fields easily and I can change fields types easily too (no migration or rollbacks needed).
- Scaling it is also easier than SQL databases.
- Also, using MongoID interface was very similar to me than ActiveRecord, which made it easy to me to adopt it.

**Comment by alex-nexus** [comment]
Got it. Do you find any issues with mongo lately? (I used it many years ago and it has many issues, both mongo and gem)

also, I have one question about how does mongo manage has_and_belongs_to_many relation?

**Comment by froveda** [comment]
@alex-nexus Not a problem at all! I can manage almost every thing I can do with ActiveRecord, and if something is not the same, there is documentation that you can find to solve it.

Regarding *has_and_belongs_to_many* relation, it saves the related objects ids in a field of a document. For example, for playlists, the songs are saved in a Array field *song_ids* with the id of the related songs:

Example using Robomongo:

<img width="1001" alt="screen shot 2017-09-13 at 15 44 32" src="https://user-images.githubusercontent.com/1401741/30394768-7e9f7d34-989a-11e7-8ee0-c96a81b6e16f.png">
