### ISSUE TITLE
API documation

### ISSUE THREAD

**Issue by alex-nexus** [froveda/ipsy_shopper#4]
Can you add some API docs, preferrably using auto-generated tools, like swagger

**Comment by froveda** [comment]
@alex-nexus I've added documentation using [rspec_api_documentation](https://github.com/zipmark/rspec_api_documentation). You can take a look at the documentation of the github repository:

https://github.com/froveda/ipsy_shopper

And you can also take a look to the documentation on a heroku site I've built (https://github.com/froveda/ipsy_shopper#api):

https://ipsy-shopper-api.herokuapp.com/doc/api/v1/index.html

What I've done is to use this gem, and generate the documentation using the acceptance tests. I've also made a change, to save all the documentation in `public/doc/api` so you can access it easily.

In the https://github.com/froveda/ipsy_shopper/blob/master/spec/rails_helper.rb file, I've configured the gem to get the versions that we have for the API, and create the documentation taking those versions into account:

```
RspecApiDocumentation.configure do |config|
  config.app = Rails.application
  config.keep_source_order = true

  config.format = :html
  config.docs_dir = Rails.root.join('public', 'doc', 'api', 'all')
  
  API_VERSIONS.each do |version|
    config.define_group(version) do |group_config|
      group_config.filter = version
      group_config.docs_dir = Rails.root.join('public', 'doc', 'api', version.to_s)
      group_config.api_name = "API #{version.upcase}"
    end
  end
end
```

So if we add a new version, and we add acceptance tests for this new version, it will generate the documentation

**Comment by alex-nexus** [comment]
sorry I didn't see this before. Great!
