### ISSUE TITLE
What happens when trying to delete a song that associated with a playlist?

### ISSUE THREAD

**Issue by alex-nexus** [froveda/ipsy_shopper#8]

**Comment by froveda** [comment]
@alex-nexus when we delete the song, it won't be part of the playlist anymore since it won't be deleted from the database, but the playlist will still exist in the system

**Comment by alex-nexus** [comment]
what happens to the foreign key on the playlist?

**Comment by froveda** [comment]
@alex-nexus the foreign key gets remove from `Playlist` `song_ids` field
